# Generated by Django 3.1.2 on 2020-10-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('myfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='unique',
            field=models.CharField(max_length=5),
        ),
    ]
